baseurl: /cube
safe: true
lsi: false
pygments: true
markdown: redcarpet
permalink: /:categories/:title
exclude:
  - CONTRIBUTING.md
  - cube.sublime-*
  - node_modules
  - Gruntfile.js
  - package.json

version: 1.1.0

