baseurl: /cube
safe: true
permalink: /:categories/:title
encoding: utf-8
exclude:
  - CONTRIBUTING.md
  - node_modules
  - gulpfile.js
  - package.json
  - README.md

title: Cube
url: https://thx.github.io/cube
version: 1.3.2

gems:
  - jekyll-feed
  - jekyll-sitemap
